# Generated by Django 6.0.1 on 2026-02-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_book_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author', 'published_date'], name='app_book_author_ca2d4b_idx'),
        ),
    ]
